### PR TITLE
Unix installation script

### PR DESCRIPTION
**Pull request by Corsol**
Create a Linux installation script that simplify database creation.
Corrected some "under_dev" db_version table change

### CODE REVIEW

**Comment by Corsol** [comment]
These tre commits fix installation scripts for ready-to-use database

**Comment by Corsol** [comment]
Another fix for ready-to-use.. i've checked it again and after some usages-test now it's full working.

**Comment by billy1arm** [comment]
@Corsol - Could you apply these changes to the develop21 branch please

**Comment by Corsol** [comment]
is it safe use the develop21 branch for master server branch source code?

**Comment by billy1arm** [comment]
I would use develop21 for both

**Pull request closed without merging**
